version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  AfterInstall:
    - location: /home/ec2-user/app/deployment/scripts/restart_nginx.sh
      timeout: 60
      runas: root
