version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing NPM dependencies...
      - npm install
  build:
    commands:
      - echo Building React app...
      - npm run build
  post_build:
    commands:
      - echo Preparing artifacts for deployment...
      - mkdir -p deployment
      - cp -r build/* deployment/
      - cp appspec.yaml deployment/
      - mkdir -p deployment/scripts
      - cp scripts/restart_nginx.sh deployment/scripts/
      - chmod +x deployment/scripts/restart_nginx.sh


artifacts:
  files:
    - deployment/**/*
