version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the app...
      - npm run build
  post_build:
    commands:
      - echo Preparing artifacts...
      - mkdir -p deployment
      - cp -r build/* deployment/
      - cp appspec.yml deployment/
      - cp -r scripts deployment/

artifacts:
  files:
    - deployment/**/*
